### ISSUE TITLE
Tilde is an operator, but is in `UNICODE_SYSTEM_UNDEFINED_SYMBOLS`

### ISSUE THREAD

**Issue by rocky** [rsmenon/pygments-mathematica#15]
See https://reference.wolfram.com/language/ref/Infix.html

It should be removed from https://github.com/rsmenon/pygments-mathematica/blob/master/mathematica/builtins.py#L5692 and added to `UNICODE_OPERATORS`.

**Comment by rsmenon** [comment]
The `~` operator is [`Infix`](https://reference.wolfram.com/language/ref/Infix.html), whereas the symbol [`Tilde`](https://reference.wolfram.com/language/ref/Tilde.html) has no built in meaning per the documentation. It is confusing, but the two are not the same.

As such, classifying it as `UNICODE_SYSTEM_UNDEFINED_SYMBOLS` (for `\[Tilde]`) or `SYSTEM_SYMBOL` (for `Tilde`) is appropriate.
